#!/bin/sh

# check whter the first input is a positive integer
if [ $1 -gt 0 ]
then
    # if is, record and pop it
    num_cols=$1
    shift
else
    # if not, give an error message and exit in an proper situation
    echo "$1: is not a positive int" 1>&2
    exit 1
fi

# print out the beginning several lines
echo "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">"
echo "<html>"
echo "  <head>"
echo "    <title>Pictures</title>"
echo "  </head>"
echo
echo "  <body>"
echo "    <h1>Pictures</h1>"
echo "<table>"

while [ "$1" != '' ]
do

    # print the prefix for a new row
    echo "    <tr>"

    # i is a counter used to count num of columns we filled
    i=0
    while ([ "$1" != '' ] && [ "$i" -lt "$num_cols" ])
    do

	# get the type of that parameter
        type=`file -b "$1" | cut -c 1-4`

        # if the file is JPEG type
        if [ "$type" = "JPEG" ]
	then
	    # a way to print out a string with '"'s inside
	    echo "         <td><img src=\"$1\" height=100></td>"  
	    # increment counter
	    i=`expr $i + 1`
  
	# if the file is another type or not exist
	else
	    # give an error message and keep running
	    echo "error: "$1": is not a valid JPEG file" 1>&2

	fi
	
	# pop the used parameter
        shift
    done

    # print the suffix for that row
    echo "    </tr>"

done

# print out the last several lines
echo "</table>"
echo "  </body> </html>"


